// <auto-generated />
namespace ComicCorner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changingdatatypeforcomicprice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changingdatatypeforcomicprice));
        
        string IMigrationMetadata.Id
        {
            get { return "202002140136178_changing data type for comicprice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
