// <auto-generated />
namespace ComicCorner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changingdatatypeofcustomeradd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changingdatatypeofcustomeradd));
        
        string IMigrationMetadata.Id
        {
            get { return "202002191506462_changing data type of customeradd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
