// <auto-generated />
namespace ComicCorner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addingreviewstableanditsforeignkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingreviewstableanditsforeignkey));
        
        string IMigrationMetadata.Id
        {
            get { return "202002171320166_adding reviews table and its foreign key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
