// <auto-generated />
namespace ComicCorner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changingpricetofloat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changingpricetofloat));
        
        string IMigrationMetadata.Id
        {
            get { return "202002201411233_changing price to float"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
