// <auto-generated />
namespace ComicCorner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _12Feb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12Feb));
        
        string IMigrationMetadata.Id
        {
            get { return "202002122112536_12 Feb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
